use clinic;
drop table if exists procedure_doctors;
drop table if exists procedures;
drop table if exists procedure_types;
drop table if exists employees;
drop table if exists hospitals;
drop table if exists persons;
drop table if exists regions;
drop table if exists countries;

drop procedure if exists proc_countries_save;
drop procedure if exists proc_get_countries;
drop procedure if exists proc_regions_save;
drop procedure if exists proc_get_regions;
drop procedure if exists proc_persons_save;
drop procedure if exists proc_get_persons;
drop procedure if exists proc_hospitals_save;
drop procedure if exists proc_get_hospitals;
drop procedure if exists proc_employees_save;
drop procedure if exists proc_get_employees;
drop procedure if exists proc_procedure_types_save;
drop procedure if exists proc_get_procedure_types;
drop procedure if exists proc_procedures_save;
drop procedure if exists proc_get_procedures;
drop procedure if exists proc_procedure_doctors_save;
drop procedure if exists proc_get_procedure_doctors;
